---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-otel-demo-adservice
spec:
  template:
    metadata:
      labels:
        owner: adteam
    spec:
      containers:
      - name: adservice
        env:
        - name: owner
          value: adteam
