apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-otel-demo
  namespace: otel-demo
spec:
  chart:
    spec:
      chart: opentelemetry-demo
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
      version: 0.9.6
  interval: 0m30s
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          # adservice
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: my-otel-demo-adservice
              labels:
                owner: "TeamA"
                priority: "P5"
                variant: "var1"
                app.kubernetes.io/part-of: "otel-demo"
                dynatrace-release-stage: "production"
                app.kubernetes.io/version: "0.6.1"
            spec:
              template:
                metadata:
                  labels:
                    owner: "TeamA"
                    priority: "P5"
                    variant: "var1"
                    app.kubernetes.io/part-of: "otel-demo"
                    dynatrace-release-stage: "production"
                    app.kubernetes.io/version: "0.6.1"
                spec:
                  containers:
                  - name: adservice
                    env:
                    - name: owner
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['owner']
                    - name: priority
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['priority']
                    - name: variant
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['variant']
                    - name: DT_RELEASE_PRODUCT
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['app.kubernetes.io/part-of']
                    - name: DT_RELEASE_STAGE
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['dynatrace-release-stage']
                    - name: DT_RELEASE_VERSION
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['app.kubernetes.io/version']
          # cartservice
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: my-otel-demo-cartservice
              labels:
                owner: "TeamB"
                priority: "P1"
                variant: "var1"
                app.kubernetes.io/part-of: "otel-demo"
                dynatrace-release-stage: "production"
                app.kubernetes.io/version: "0.6.1-beta"
            spec:
              template:
                metadata:
                  labels:
                    owner: "TeamB"
                    priority: "P1"
                    variant: "var1"
                    app.kubernetes.io/part-of: "otel-demo"
                    dynatrace-release-stage: "production"
                    app.kubernetes.io/version: "0.6.1-beta"
                spec:
                  containers:
                  - name: cartservice
                    env:
                    - name: owner
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['owner']
                    - name: priority
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['priority']
                    - name: variant
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['variant']
                    - name: DT_RELEASE_PRODUCT
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['app.kubernetes.io/part-of']
                    - name: DT_RELEASE_STAGE
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['dynatrace-release-stage']
                    - name: DT_RELEASE_VERSION
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['app.kubernetes.io/version']
          # checkoutservice
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: my-otel-demo-checkoutservice
              labels:
                owner: "BizOps"
                priority: "P1"
                variant: "var1"
                app.kubernetes.io/part-of: "otel-demo"
                dynatrace-release-stage: "production"
                app.kubernetes.io/version: "0.6.1-beta"
            spec:
              template:
                metadata:
                  labels:
                    owner: "BizOps"
                    priority: "P1"
                    variant: "var1"
                    app.kubernetes.io/part-of: "otel-demo"
                    dynatrace-release-stage: "production"
                    app.kubernetes.io/version: "0.6.1-beta"
                spec:
                  containers:
                  - name: checkoutservice
                    env:
                    - name: owner
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['owner']
                    - name: priority
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['priority']
                    - name: variant
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['variant']
                    - name: DT_RELEASE_PRODUCT
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['app.kubernetes.io/part-of']
                    - name: DT_RELEASE_STAGE
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['dynatrace-release-stage']
                    - name: DT_RELEASE_VERSION
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['app.kubernetes.io/version']
          # currencyservice
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: my-otel-demo-currencyservice
              labels:
                owner: "TeamC"
                priority: "P3"
                variant: "var1"
                app.kubernetes.io/part-of: "otel-demo"
                dynatrace-release-stage: "production"
                app.kubernetes.io/version: "0.6.1-beta"
            spec:
              template:
                metadata:
                  labels:
                    owner: "TeamC"
                    priority: "P3"
                    variant: "var1"
                    app.kubernetes.io/part-of: "otel-demo"
                    dynatrace-release-stage: "production"
                    app.kubernetes.io/version: "0.6.1-beta"
                spec:
                  containers:
                  - name: currencyservice
                    env:
                    - name: owner
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['owner']
                    - name: priority
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['priority']
                    - name: variant
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['variant']
                    - name: DT_RELEASE_PRODUCT
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['app.kubernetes.io/part-of']
                    - name: DT_RELEASE_STAGE
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['dynatrace-release-stage']
                    - name: DT_RELEASE_VERSION
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['app.kubernetes.io/version']
          # emailservice
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: my-otel-demo-emailservice
              labels:
                owner: "TeamC"
                priority: "P3"
                variant: "var1"
                app.kubernetes.io/part-of: "otel-demo"
                dynatrace-release-stage: "production"
                app.kubernetes.io/version: "0.6.1-beta"
            spec:
              template:
                metadata:
                  labels:
                    owner: "TeamC"
                    priority: "P3"
                    variant: "var1"
                    app.kubernetes.io/part-of: "otel-demo"
                    dynatrace-release-stage: "production"
                    app.kubernetes.io/version: "0.6.1-beta"
                spec:
                  containers:
                  - name: emailservice
                    env:
                    - name: owner
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['owner']
                    - name: priority
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['priority']
                    - name: variant
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['variant']
                    - name: DT_RELEASE_PRODUCT
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['app.kubernetes.io/part-of']
                    - name: DT_RELEASE_STAGE
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['dynatrace-release-stage']
                    - name: DT_RELEASE_VERSION
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['app.kubernetes.io/version']
                              