apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-otel-demo
  namespace: otel-demo
spec:
  chart:
    spec:
      chart: opentelemetry-demo
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
      version: 0.9.6
  interval: 0m30s
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: my-otel-demo-adservice
              labels:
                owner: "TeamA"
            spec:
              template:
                metadata:
                  labels:
                    owner: "TeamA"
                spec:
                  containers:
                  - name: adservice
                    env:
                    - name: owner
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.labels['owner']
                              