---
apiVersion: lifecycle.keptn.sh/v1alpha1
kind: KeptnTaskDefinition
metadata:
  name: keptn-task1
  namespace: otel-demo
spec:
  function:
    inline:
      code: |
        console.log(">> Post-Deployment Task has been executed 2");