apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  namespace: jobs
  annotations:
    app.kubernetes.io/version: "0.0.1"
    keptn.sh/workload: "pi-job"  
    keptn.sh/pre-deployment-tasks: "pre-deployment-hello"
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4