apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-otel-demo
  namespace: otel-demo
spec:
  postRenderers:
    - kustomize:
      patchesStrategicMerge:
        - kind: Deployment
          metadata:
            name: my-otel-demo-adservice
            labels:
              owner: teamA