---
apiVersion: keptn.sh/v1
kind: KeptnEvaluationProvider
metadata:
  name: prometheus
  namespace: keptn-lifecycle-toolkit-system
spec:
  targetServer: "http://prometheus-operated.monitoring.svc.cluster.local:9090"