apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: otel-col
  namespace: keptn-lifecycle-toolkit-system
spec:
  chart:
    spec:
      chart: opentelemetry-collector
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
      version: 0.38.0
  interval: 1m00s
  values:
    service:
      type: ClusterIP
    extraEnvs:
      - name: "DT_OTLP_ENDPOINT"
        valueFrom:
          secretKeyRef:
            key: "DT_OTLP_ENDPOINT"
            name: "dynatrace-connection-details"
      - name: "DT_METRICS_ENDPOINT"
        valueFrom:
          secretKeyRef:
            key: "DT_METRICS_ENDPOINT"
            name: "dynatrace-connection-details"
      - name: "DT_API_TOKEN"
        valueFrom:
          secretKeyRef:
            key: "DT_API_TOKEN"
            name: "dynatrace-connection-details"
      - name: "OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE"
        valueFrom:
          secretKeyRef:
            key: "OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE"
            name: "dynatrace-connection-details"
    mode: daemonset
    config:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
      exporters:
        # otlp/http exporter to export traces to Dynatrace.
        otlphttp/dynatrace:
          endpoint: "${DT_OTLP_ENDPOINT}"
          headers:
            Authorization: "Api-Token ${DT_API_TOKEN}"
        # Dynatrace metrics exporter
        dynatrace:
          endpoint: "${DT_METRICS_ENDPOINT}"
          api_token: "${DT_API_TOKEN}"
      processors:
        # Processor to generate (delta temporality) metrics from
        # spans.
        # dummy comment
        spanmetrics/dynatrace:
          metrics_exporter: dynatrace
          aggregation_temporality: AGGREGATION_TEMPORALITY_DELTA
      service:
        pipelines:
          # trace pipeline for exporting to dynatrace. 
          traces/dynatrace: 
            receivers: [otlp] 
            processors: [batch, spanmetrics/dynatrace] 
            exporters: [otlphttp/dynatrace] 
          # metrics pipeline for exporting to dynatrace. 
          metrics/dynatrace: 
            receivers: [otlp] 
            processors: [batch] 
            exporters: [dynatrace]