apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-otel-demo
  namespace: otel-demo
spec:
  chart:
    spec:
      chart: opentelemetry-demo
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
      version: 0.9.6
  values:
    # disable currency service
    components:
      currencyService:
        enabled: false
  interval: 1m0s