apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-otel-demo
  namespace: otel-demo
spec:
  chart:
    spec:
      chart: opentelemetry-demo
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
      version: 0.9.6
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: my-otel-demo-adservice
              labels:
                "owner": "teamA"
            spec:
              containers:
              - name: my-otel-demo-adservice
                env:
                - name: "foo"
                  value: "bar"
  interval: 1m0s
