apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-otel-demo
  namespace: otel-demo
spec:
  chart:
    spec:
      chart: opentelemetry-demo
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
      version: 0.9.6
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - set-adservice-owner.yaml
  interval: 0m30s