apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otel-demo
resources:
  - helmsource.yaml
  - helmrelease.yaml
  - namespace.yaml
patchesStrategicMerge:
  - "set-adservice-owner.yaml"