---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-otel-demo-adservice
  labels:
    owner: "Team A"
spec:
  template:
    metadata:
      labels:
        owner: "Team A"
    spec:
      containers:
      - name: adservice
        env:
        - name: owner
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['owner']