---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-otel-demo-adservice
spec:
  template:
    metadata:
      labels:
        owner: "Team A1"
    spec:
      containers:
      - name: adservice
        env:
        - name: owner
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['owner']