apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dynatrace
  namespace: dynatrace
spec:
  interval: 1h0m0s
  url: https://raw.githubusercontent.com/Dynatrace/dynatrace-operator/master/config/helm/repos/stable
